### ISSUE TITLE
Prayer-times widget

### ISSUE THREAD

**Issue by moiz-qureshi** [Mosque-Screens/Mosque-Screen#12]
It would be cool to widgetize the prayer-times view. Something similar to the Iqama timing widget on this this site https://masjidalrahman.com/#masjidhub 

That way people can paste their timing in this sheet https://docs.google.com/spreadsheets/d/1yVlGjnEhKLi5DSOuJMm7-ec5-iFvuiR7WkbzMdbFP9s/edit?usp=sharing and it will update the website as well. 

Would be pretty neat to have a centralized place to upload the schedule and have it show in numerous places.

**Comment by DilwoarH** [comment]
I think you're on to something. At the moment this project is fully focused on the screens themselves. Maybe in the future we can have a `/widget` mode. We're happy to accept a contribution if you already have the code?

**Comment by DilwoarH** [comment]
We've implemented this now https://github.com/Mosque-Screens/Mosque-Screen#add-to-website
